[package]
name = "expense-tracker"
version = "0.1.0"
authors = ["Philip Van Raalte <phil.vanraalte@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.1", features = ["sqlite"] }
dotenv = "0.13"
